# Generated by Django 4.2.5 on 2023-10-25 19:00

from django.db import migrations, models
import foodspots.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FoodSpot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default='default/restarant.jpg', upload_to=foodspots.models.upload_to)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('time', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255, unique=True)),
                ('reel', models.URLField(blank=True, null=True, unique=True)),
                ('categories', models.ManyToManyField(to='foodspots.category')),
            ],
        ),
    ]
