# Generated by Django 4.1.3 on 2023-08-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodspots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodspot',
            name='reel',
            field=models.URLField(blank=True, null=True),
        ),
    ]
